### ISSUE TITLE
multi-class classification

### ISSUE THREAD

**Issue by David-zreo** [Denbergvanthijs/imbDRL#1]
Hello,friend.I have a question.  how to change this code to deal with the problem of multi-class classification?

**Comment by Denbergvanthijs** [comment]
Hi David, currently imbDRL only works for binary classification. The imbalance ratio, (the number of instances for the minority class divided by the number of instances for the majority class), is not defined for more than two classes. 

You could however guess the reward for each of your classes and write your own environment based on: https://github.com/Denbergvanthijs/imbDRL/blob/master/imbDRL/environments/classifierenv.py

**Comment by David-zreo** [comment]
Thank you, my friend. I will try to write my own environment .
