### ISSUE TITLE
[Errno 2] No such file or directory: './models/20220204_182039.pkl'

### ISSUE THREAD

**Issue by LorisAlif** [Denbergvanthijs/imbDRL#2]
hello, i got this problem. Does this means i have to use a pre-trained model or  there's something wrong with the directory issues?

**Comment by Denbergvanthijs** [comment]
Could you provide a code example to reproduce this?

**Comment by LorisAlif** [comment]
Turns out i need to create folder manually named  'model' in order to solve the error. Now it's running properly. Sorry for the inconvenience

**Comment by Denbergvanthijs** [comment]
That's probably a bug that needs solving. Thank you for using imbDRL!
