### ISSUE TITLE
How to extend the code to work on other datasets

### ISSUE THREAD

**Issue by chariot1498** [Denbergvanthijs/imbDRL#5]
I was wondering what all i need to change to make the code work on other datasets like mozilla4 etc.

**Comment by Denbergvanthijs** [comment]
The easiest way is to copy one of the examples and change the code to load your own data, e.g. take a look at the MNIST example:

https://github.com/Denbergvanthijs/imbDRL/blob/master/imbDRL/examples/ddqn/train_mnist.py
