### ISSUE TITLE
Log reward for each environment step.

### ISSUE THREAD

**Issue by iMac-ant** [Denbergvanthijs/imbDRL#6]
Hi @Denbergvanthijs, could you suggest me an easy way to log the reward value for each step?

**Comment by Denbergvanthijs** [comment]
A quick and dirty solution would be to print the reward within the _step() function of the environment:

https://github.com/Denbergvanthijs/imbDRL/blob/bedf1c7bb83a75427d2ea3ed07b17e2ef55f8448/imbDRL/environments/classifierenv.py#L59-L93

Otherwise, a callback function would be better
